// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qNDYtsK9jOsT2qerR3Yew--9C-EJ9pA',
    appId: '1:768970769332:web:f91f04050c50f6c13068e1',
    messagingSenderId: '768970769332',
    projectId: 'empyrean-surge-395513',
    authDomain: 'empyrean-surge-395513.firebaseapp.com',
    storageBucket: 'empyrean-surge-395513.appspot.com',
    measurementId: 'G-D309E59W0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhihhs4sQafVQFfXNW-ZNYL8OB5VrSrkc',
    appId: '1:768970769332:android:48e61993647ddd773068e1',
    messagingSenderId: '768970769332',
    projectId: 'empyrean-surge-395513',
    storageBucket: 'empyrean-surge-395513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbXohR18yZYDkYmJk2nwOJGTK-j6SuQw',
    appId: '1:768970769332:ios:0196372aca467da03068e1',
    messagingSenderId: '768970769332',
    projectId: 'empyrean-surge-395513',
    storageBucket: 'empyrean-surge-395513.appspot.com',
    iosClientId: '768970769332-03g8jjqq6fmdlm10cq7no6abo3j1qbvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trywithkokoExpense2',
  );
}
